-- Top 20 Rated Restaurants
select Restaurant, Avg_ratings, Total_ratings
from swiggy_final
order by Avg_ratings desc
limit 20;

-- Most Expensive Restaurants
select Restaurant, Price
from swiggy_final
order by Price desc
limit 10;

-- Restaurants with the Most Reviews
select Restaurant, Total_ratings
from swiggy_final
order by Total_ratings desc
limit 10;

-- Average Price Per Person in Each City
select City, AVG(Price) AS Avg_Price
from swiggy_final
group by City;

-- Average Ratings Per Food Type
select Food_type, AVG(Avg_ratings) AS Avg_Ratings
from swiggy_final
group by Food_type;

-- Number of Restaurants by Area
select Area, COUNT(Restaurant) AS Num_Restaurants
from swiggy_final
group by  Area;

-- Popular Food Types in Each City
select City, Food_type, COUNT(*) AS Num_Restaurants
from swiggy_final
group by City, Food_type
order by City, Num_Restaurants DESC;

-- Average Delivery Time for Restaurants with More than 1000 Total Ratings
select AVG(Delivery_time) AS Avg_Delivery_Time
from swiggy_final
where Total_ratings > 1000;

-- Restaurants with the Unique Food Types
select Restaurant, GROUP_CONCAT(DISTINCT Food_type ORDER BY Food_type SEPARATOR ', ') AS Food_types
from swiggy_final
group by Restaurant
order by Restaurant;

-- Most Popular Food Types Overall
select Food_type, COUNT(*) AS Num_Restaurants
from swiggy_final
group by Food_type
order by Num_Restaurants desc
LIMIT 10;

-- Average Ratings and Prices by Area
SELECT Area, AVG(Avg_ratings) AS Avg_Rating, AVG(Price) AS Avg_Price
FROM swiggy_final
GROUP BY Area
ORDER BY Avg_Rating DESC;

-- Restaurants with the Highest Ratings in Each Area
select Area, Restaurant, Avg_ratings
from (
select Area, Restaurant, Avg_ratings,
ROW_NUMBER() OVER (PARTITION BY Area ORDER BY Avg_ratings DESC) AS RowNum
FROM swiggy_final
) AS Ranked
WHERE RowNum = 1;

-- How many Restaurants have the word 'pizza' in their name?
select count(Restaurant) as pizza_restaurents from swiggy_final 
where Restaurant like '%pizza%';

-- which restaurent have more Avg_ratings in bangalore city?
select City,Restaurant,Avg_ratings  from swiggy_final
where City='Bangalore'
order by Avg_ratings desc
limit 10;

-- Restaurant with food type Chinese 
select City,Restaurant from swiggy_final 
where Food_type like 'Chinese';

-- How many Restaurent have a rating greater than  4.5?
select count(Restaurant) from swiggy_final
where Avg_ratings>4.5; 

-- which is the top 1 city with the highest number of Restaurants?
select City,count(Restaurant) as restaurent_count from swiggy_final 
group by City
order by restaurent_count desc
limit 1;

-- Which restaurent supply chinese food in Mumbai city?
select City,Restaurant from swiggy_final 
where Food_type like 'Chinese' and City='Mumbai';

-- which restaurent have the highest average price for all items?
select distinct Restaurant,avg(price) as Avg_price from swiggy_final
group by Restaurant
order by Avg_price desc
limit 1;

-- Restaurants with maximum delivery time and minimum delivery time
select Restaurant, City, MAX(Delivery_time) AS Max_Delivery_Time
from swiggy_final
group by Restaurant, City
order by Max_Delivery_Time desc;

-- Number of restaurants in each city serving indian food
select City, count(Restaurant) from swiggy_final
where Food_type like 'indian'
group by city  order by count(Restaurant) desc  ;


-- Find the areas with most no of restaurants and least no of restaurants
select Area,City ,count(Restaurant) from swiggy_final
group by Area,City
order by count(Restaurant) desc;


-- Find the address in each city in which maximum order takes place
select Address ,count(Address),City from swiggy_final
group by Address,City order by count(*) desc;


-- Percentage of revenue generated by each city
select City, sum(price) as Total_price,round(sum(Price)/(select sum(Price)
from swiggy_final)*100,2) as Total_percentage 
from swiggy_final group by City
order by sum(Price) desc ;
  
  
-- What is the average total rating for restaurants in each price range
 select 
    case 
        when Price < 500 then 'Low'
        when Price >= 500 and Price < 2000 then 'Medium'
        else 'High'
    end as price_range,
    ROUND(AVG(Total_ratings), 0) AS avg_total_rating
from 
    swiggy_final
group by 
    price_range;

-- find the restaurant in each city,area that serves biryani ?
select Restaurant,City,Area from swiggy_final
where Food_type like 'Biryani';

-- create a view table and that shows the count of city?
create view City_Counts as select City,count(City)
from swiggy_final
group by City;
select * from City_Counts;
